export const AWAITING_VALUE: 'AWAITING_VALUE' = 'AWAITING_VALUE'
export const VALUE_RECEIVED: 'VALUE_RECEIVED' = 'VALUE_RECEIVED'

export const AWAIT_VALUE: 'AWAIT_VALUE' = 'AWAIT_VALUE'
export const RECEIVE_VALUE: 'RECEIVE_VALUE' = 'RECEIVE_VALUE'

export const ASYNC_COMMAND: 'ASYNC_COMMAND' = 'ASYNC_COMMAND'
export const ASYNC_AWAITING_VALUE: 'ASYNC_AWAITING_VALUE' = 'ASYNC_AWAITING_VALUE'
export const ASYNC_VALUE_RECEIVED: 'ASYNC_VALUE_RECEIVED' = 'ASYNC_VALUE_RECEIVED'
