export const AWAITING_RESULT: 'AWAITING_RESULT' = 'AWAITING_RESULT'
export const RESULT_RECEIVED: 'RESULT_RECEIVED' = 'RESULT_RECEIVED'

export const AWAIT_RESULT: 'AWAIT_RESULT' = 'AWAIT_RESULT'
export const RECEIVE_RESULT: 'RECEIVE_RESULT' = 'RECEIVE_RESULT'
